//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShadowRunHelperViewer.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShadowRunHelperViewer.Strings.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string Char_View_Pivot_Aktion_Label {
            get {
                return ResourceManager.GetString("Char_View_Pivot_Aktion.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Items ähnelt.
        /// </summary>
        public static string Char_View_Pivot_Item_Label {
            get {
                return ResourceManager.GetString("Char_View_Pivot_Item.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battle ähnelt.
        /// </summary>
        public static string Char_View_Pivot_Kampf_Label {
            get {
                return ResourceManager.GetString("Char_View_Pivot_Kampf.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        public static string Char_View_Pivot_Notizen_Label {
            get {
                return ResourceManager.GetString("Char_View_Pivot_Notizen.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Person ähnelt.
        /// </summary>
        public static string Char_View_Pivot_Person_Label {
            get {
                return ResourceManager.GetString("Char_View_Pivot_Person.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Char_View_Pivot_Settings_Label {
            get {
                return ResourceManager.GetString("Char_View_Pivot_Settings.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename ähnelt.
        /// </summary>
        public static string Ui_Admin_Filename_Text {
            get {
                return ResourceManager.GetString("Ui_Admin_Filename.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filepath ähnelt.
        /// </summary>
        public static string Ui_Admin_Filepath_Text {
            get {
                return ResourceManager.GetString("Ui_Admin_Filepath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string UI_Btn_Bearbeiten_Content {
            get {
                return ResourceManager.GetString("UI_Btn_Bearbeiten.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Links ähnelt.
        /// </summary>
        public static string UI_Btn_Bearbeiten_LinkedThings_Content {
            get {
                return ResourceManager.GetString("UI_Btn_Bearbeiten_LinkedThings.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Ammunition ähnelt.
        /// </summary>
        public static string UI_Btn_Bearbeiten_Munition_Content {
            get {
                return ResourceManager.GetString("UI_Btn_Bearbeiten_Munition.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string UI_Btn_Loeschen_Content {
            get {
                return ResourceManager.GetString("UI_Btn_Loeschen.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string UI_Char_Btn_Speichern_Label {
            get {
                return ResourceManager.GetString("UI_Char_Btn_Speichern.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mental ähnelt.
        /// </summary>
        public static string UI_Char_Schaden_Geist_Text {
            get {
                return ResourceManager.GetString("UI_Char_Schaden_Geist.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Physical ähnelt.
        /// </summary>
        public static string UI_Char_Schaden_Koerper_Text {
            get {
                return ResourceManager.GetString("UI_Char_Schaden_Koerper.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Matrix ähnelt.
        /// </summary>
        public static string UI_Char_Schaden_Matrix_Text {
            get {
                return ResourceManager.GetString("UI_Char_Schaden_Matrix.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Damage: ähnelt.
        /// </summary>
        public static string UI_Char_Schaden_Text {
            get {
                return ResourceManager.GetString("UI_Char_Schaden.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete all Chars ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_Btn_Alle_Chars_Loeschen_Label {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_Btn_Alle_Chars_Loeschen.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Example Char ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_Btn_Create_ExampleChar_Label {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_Btn_Create_ExampleChar.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load the example/turorial character sheet into the current folder ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_Btn_Create_ExampleChar_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_Btn_Create_ExampleChar.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV Import ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_Btn_CSV_Import_Label {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_Btn_CSV_Import.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Char Import ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_Btn_Datei_Import_Label {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_Btn_Datei_Import.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new char ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_Btn_Neu_Label {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_Btn_Neu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use it to create a new character sheet ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_Btn_Neu_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_Btn_Neu.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die modification date ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_E_FileDate_Text {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_E_FileDate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die file name ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_E_FileName_Text {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_E_FileName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die file size ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_E_FileSize_Text {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_E_FileSize.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current savefiles: ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_Einleitung1_Text {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_Einleitung1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available savefiles: ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_Einleitung2_Text {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_Einleitung2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Intern ähnelt.
        /// </summary>
        public static string UI_CharVerwaltung_Intern_Save_Display_String {
            get {
                return ResourceManager.GetString("UI_CharVerwaltung_Intern_Save_Display_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string UI_CLS_Close_Content {
            get {
                return ResourceManager.GetString("UI_CLS_Close.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string UI_CNT_Close_Content {
            get {
                return ResourceManager.GetString("UI_CNT_Close.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string UI_CNT_Reset_Content {
            get {
                return ResourceManager.GetString("UI_CNT_Reset.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open notifications ähnelt.
        /// </summary>
        public static string UI_Cntnt_GoTo_Notifications_Content {
            get {
                return ResourceManager.GetString("UI_Cntnt_GoTo_Notifications.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string Ui_DB_Finish_Label {
            get {
                return ResourceManager.GetString("Ui_DB_Finish.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy and Exit ähnelt.
        /// </summary>
        public static string Ui_DB_FinishClose_Label {
            get {
                return ResourceManager.GetString("Ui_DB_FinishClose.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help on/off ähnelt.
        /// </summary>
        public static string Ui_DB_Help_Label {
            get {
                return ResourceManager.GetString("Ui_DB_Help.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        public static string Ui_DB_Nav_Label {
            get {
                return ResourceManager.GetString("Ui_DB_Nav.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV Export ähnelt.
        /// </summary>
        public static string UI_Label_CSV_Export_Label {
            get {
                return ResourceManager.GetString("UI_Label_CSV_Export.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saves this character sheet in CSV format (Excel compatible) in a folder. Several files are created. ähnelt.
        /// </summary>
        public static string UI_Label_CSV_Export_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_Label_CSV_Export.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string UI_Label_DeleteChar_Label {
            get {
                return ResourceManager.GetString("UI_Label_DeleteChar.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletes this file. ähnelt.
        /// </summary>
        public static string UI_Label_DeleteChar_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_Label_DeleteChar.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Char Export ähnelt.
        /// </summary>
        public static string UI_Label_File_Export_Label {
            get {
                return ResourceManager.GetString("UI_Label_File_Export.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy this file to another location. ähnelt.
        /// </summary>
        public static string UI_Label_File_Export_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_Label_File_Export.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load ähnelt.
        /// </summary>
        public static string UI_Label_LoadChar_Label {
            get {
                return ResourceManager.GetString("UI_Label_LoadChar.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opens this file. ähnelt.
        /// </summary>
        public static string UI_Label_LoadChar_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_Label_LoadChar.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        public static string UI_Label_Rename_Label {
            get {
                return ResourceManager.GetString("UI_Label_Rename.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administration ähnelt.
        /// </summary>
        public static string Ui_Nav_Admin_Label {
            get {
                return ResourceManager.GetString("Ui_Nav_Admin.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character Sheet ähnelt.
        /// </summary>
        public static string Ui_Nav_Char_Label {
            get {
                return ResourceManager.GetString("Ui_Nav_Char.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Ui_Nav_Settings_Label {
            get {
                return ResourceManager.GetString("Ui_Nav_Settings.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App ähnelt.
        /// </summary>
        public static string UI_Optionen_App_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_App.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Storeentry for this App ähnelt.
        /// </summary>
        public static string UI_Optionen_AppLinkBtn_Content {
            get {
                return ResourceManager.GetString("UI_Optionen_AppLinkBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-Save current char at changes ähnelt.
        /// </summary>
        public static string UI_Optionen_AutoSave_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_AutoSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After a change, the specified time is waited until your char is saved. If you change many things quickly, then a larger value is better. A value between 2 and 10 seconds is okay. ähnelt.
        /// </summary>
        public static string UI_Optionen_AutoSave_Tip {
            get {
                return ResourceManager.GetString("UI_Optionen_AutoSave.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Watingtime for changes in seconds ähnelt.
        /// </summary>
        public static string UI_Optionen_AutoSaveInterval_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_AutoSaveInterval.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BackUp versioning ähnelt.
        /// </summary>
        public static string UI_Optionen_BACKUP_VERSIONING_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_BACKUP_VERSIONING.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Each time Run or Karma is changed, a copy of the char is created in a BackUp folder. ähnelt.
        /// </summary>
        public static string UI_Optionen_BACKUP_VERSIONING_Tip {
            get {
                return ResourceManager.GetString("UI_Optionen_BACKUP_VERSIONING.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activate Beta-Features ähnelt.
        /// </summary>
        public static string UI_Optionen_Beta_Features_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Beta_Features.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rate this App at the Store ähnelt.
        /// </summary>
        public static string UI_Optionen_Bewerten_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Bewerten.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This app does not collect any personal information and therefore does not disclose it.
        ///This app can be used to open files and folders on the file system. The app stores those folders and files only for later use. All files remain on the file system or Microsoft account. ähnelt.
        /// </summary>
        public static string UI_Optionen_Datenschutz_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Datenschutz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug Mode ähnelt.
        /// </summary>
        public static string UI_Optionen_Debug_Mode_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Debug_Mode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables various Notifications about time and stuff ähnelt.
        /// </summary>
        public static string UI_Optionen_Debug_Mode_Tip {
            get {
                return ResourceManager.GetString("UI_Optionen_Debug_Mode.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable tips ähnelt.
        /// </summary>
        public static string UI_Optionen_Disable_Tips_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Disable_Tips.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable the tips while loading. ähnelt.
        /// </summary>
        public static string UI_Optionen_Disable_Tips_Tip {
            get {
                return ResourceManager.GetString("UI_Optionen_Disable_Tips.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hold Char Page active ähnelt.
        /// </summary>
        public static string UI_Optionen_DisplayRequest_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_DisplayRequest.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prevent the Screen from locking ähnelt.
        /// </summary>
        public static string UI_Optionen_DisplayRequest_Tip {
            get {
                return ResourceManager.GetString("UI_Optionen_DisplayRequest.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit after adding ähnelt.
        /// </summary>
        public static string UI_Optionen_EditAfterAdd_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_EditAfterAdd.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error not specified in detail:  ähnelt.
        /// </summary>
        public static string UI_Optionen_EditAfterAdd_Tip {
            get {
                return ResourceManager.GetString("UI_Optionen_EditAfterAdd.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add date and time to filename ähnelt.
        /// </summary>
        public static string UI_Optionen_FileNameUseDate_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_FileNameUseDate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add progress to filename ähnelt.
        /// </summary>
        public static string UI_Optionen_FileNameUseProgres_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_FileNameUseProgres.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file name is generated automatically and contains: Name of the char, karma, number of runs. ähnelt.
        /// </summary>
        public static string UI_Optionen_FileNameUseProgres_Tip {
            get {
                return ResourceManager.GetString("UI_Optionen_FileNameUseProgres.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Char ähnelt.
        /// </summary>
        public static string UI_Optionen_Group_Char_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Group_Char.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die file management ähnelt.
        /// </summary>
        public static string UI_Optionen_Group_File_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Group_File.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving and loading ähnelt.
        /// </summary>
        public static string UI_Optionen_Group_IO_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Group_IO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other ähnelt.
        /// </summary>
        public static string UI_Optionen_Group_Other_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Group_Other.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App owener ähnelt.
        /// </summary>
        public static string UI_Optionen_Inhaber_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Inhaber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sync intern files ähnelt.
        /// </summary>
        public static string UI_Optionen_Intern_Sync_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Intern_Sync.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will synchronize the files you have stored internally over all your Windows 10 devices. Synchronization occurs only if you have enabled the general sync option in WIndows and both devices have sufficient power and a Internetconnection. ähnelt.
        /// </summary>
        public static string UI_Optionen_Intern_Sync_Tip {
            get {
                return ResourceManager.GetString("UI_Optionen_Intern_Sync.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die email ähnelt.
        /// </summary>
        public static string UI_Optionen_Kontakt_Mail_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Kontakt_Mail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die write email ähnelt.
        /// </summary>
        public static string UI_Optionen_KontaktBtn_Content {
            get {
                return ResourceManager.GetString("UI_Optionen_KontaktBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ShadowRun is a registered trademark of Pegasus Games.
        ///Icons made by Freepik https://www.flaticon.com are licensed by Creative Commons BY 3.0. ähnelt.
        /// </summary>
        public static string UI_Optionen_Legal_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Legal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load last used char at App start ähnelt.
        /// </summary>
        public static string UI_Optionen_LoadOnStart_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_LoadOnStart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The char that was active when the app was closed is loaded at startup. Attention, this increases the app loading time. ähnelt.
        /// </summary>
        public static string UI_Optionen_LoadOnStart_Tip {
            get {
                return ResourceManager.GetString("UI_Optionen_LoadOnStart.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die more of my apps ähnelt.
        /// </summary>
        public static string UI_Optionen_MoreAppsBtn_Content {
            get {
                return ResourceManager.GetString("UI_Optionen_MoreAppsBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intern Save ähnelt.
        /// </summary>
        public static string UI_Optionen_Ordnermode_OffText {
            get {
                return ResourceManager.GetString("UI_Optionen_Ordnermode.OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extern Save ähnelt.
        /// </summary>
        public static string UI_Optionen_Ordnermode_OnText {
            get {
                return ResourceManager.GetString("UI_Optionen_Ordnermode.OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path ähnelt.
        /// </summary>
        public static string UI_Optionen_Ordnermode_Pfad_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Ordnermode_Pfad.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save at folder ähnelt.
        /// </summary>
        public static string UI_Optionen_Ordnermode_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Ordnermode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a Exernen storage folder. ähnelt.
        /// </summary>
        public static string UI_Optionen_Ordnermode_Tip {
            get {
                return ResourceManager.GetString("UI_Optionen_Ordnermode.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rate this App ähnelt.
        /// </summary>
        public static string UI_Optionen_RateBtn_Content {
            get {
                return ResourceManager.GetString("UI_Optionen_RateBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original Exception ähnelt.
        /// </summary>
        public static string UI_Optionen_ThrownException_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_ThrownException.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string UI_Optionen_Toggle_OffContent {
            get {
                return ResourceManager.GetString("UI_Optionen_Toggle.OffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string UI_Optionen_Toggle_OnContent {
            get {
                return ResourceManager.GetString("UI_Optionen_Toggle.OnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read &quot;Char Administration&quot; Guide ähnelt.
        /// </summary>
        public static string UI_Optionen_TutorialMainShown_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_TutorialMainShown.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Buy_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Buy.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you have the possibility to make purchases. You can turn off advertising with the first two options. The third option supports the developer and adds an exclusive Badge to your app. ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Buying_Header_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Buying_Header.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Note: Having apps in the store costs 18€ per year. It would be cool if the app would at least cover the costs. ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Buying_Note_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Buying_Note.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose categories ähnelt.
        /// </summary>
        public static string UI_Optionen_U_CharPageConfig_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_CharPageConfig.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy Policy ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Datenschutz_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Datenschutz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Einstellungen_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Einstellungen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hold the mouse or finger on a ? to get more information. ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Einstellungen_Tip_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Einstellungen_Tip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Hilfe_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Hilfe.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Infos_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Infos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Kontakt_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Kontakt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Notifications_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Notifications.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legal ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Rechtliches_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Rechtliches.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics ähnelt.
        /// </summary>
        public static string UI_Optionen_U_Statistics_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_U_Statistics.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string UI_Optionen_Version_Text {
            get {
                return ResourceManager.GetString("UI_Optionen_Version.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reload to see changes ähnelt.
        /// </summary>
        public static string UI_Settings_Btn_Speichern_Content {
            get {
                return ResourceManager.GetString("UI_Settings_Btn_Speichern.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of appstarts ähnelt.
        /// </summary>
        public static string UI_Statistics_AppStart_Text {
            get {
                return ResourceManager.GetString("UI_Statistics_AppStart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of new chars ähnelt.
        /// </summary>
        public static string UI_Statistics_Creations_Text {
            get {
                return ResourceManager.GetString("UI_Statistics_Creations.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of deleted chars ähnelt.
        /// </summary>
        public static string UI_Statistics_Deletions_Text {
            get {
                return ResourceManager.GetString("UI_Statistics_Deletions.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of loaded chars ähnelt.
        /// </summary>
        public static string UI_Statistics_Loadings_Text {
            get {
                return ResourceManager.GetString("UI_Statistics_Loadings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of saved chars ähnelt.
        /// </summary>
        public static string UI_Statistics_Savings_Text {
            get {
                return ResourceManager.GetString("UI_Statistics_Savings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Seperator ähnelt.
        /// </summary>
        public static string UI_TxT_Cat_AddSep_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Cat_AddSep.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die alphabeticly ähnelt.
        /// </summary>
        public static string UI_TxT_Cat_Order_ABC_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Cat_Order_ABC.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load saved order ähnelt.
        /// </summary>
        public static string UI_TxT_Cat_Order_Orig_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Cat_Order_Orig.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loads the previously saved sequence of the entry of this category. ähnelt.
        /// </summary>
        public static string UI_TxT_Cat_Order_Orig_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_Cat_Order_Orig.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save current order ähnelt.
        /// </summary>
        public static string UI_TxT_Cat_Order_Save_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Cat_Order_Save.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saves the current sequence of the entry of this category. ähnelt.
        /// </summary>
        public static string UI_TxT_Cat_Order_Save_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_Cat_Order_Save.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die after &quot;type&quot; ähnelt.
        /// </summary>
        public static string UI_TxT_Cat_Order_Type_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Cat_Order_Type.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die truncate category ähnelt.
        /// </summary>
        public static string UI_TxT_Cat_Truncate_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Cat_Truncate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This clears the entire category. ähnelt.
        /// </summary>
        public static string UI_TxT_Cat_Truncate_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_Cat_Truncate.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deselect All ähnelt.
        /// </summary>
        public static string UI_TxT_Cat_UncheckAll_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Cat_UncheckAll.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This collapses all expanded entries. ähnelt.
        /// </summary>
        public static string UI_TxT_Cat_UncheckAll_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_Cat_UncheckAll.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character sheet settings ähnelt.
        /// </summary>
        public static string UI_TxT_CharSettings_Text {
            get {
                return ResourceManager.GetString("UI_TxT_CharSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This allows you to configure this view. ähnelt.
        /// </summary>
        public static string UI_TxT_CharSettings_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_CharSettings.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string UI_TxT_Copy_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Copy.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV Export (just selected) ähnelt.
        /// </summary>
        public static string UI_TxT_CSV_Cat_Export_Selected_Text {
            get {
                return ResourceManager.GetString("UI_TxT_CSV_Cat_Export_Selected.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saves selected entries of this category in CSV format (Excel compatible) in a folder. ähnelt.
        /// </summary>
        public static string UI_TxT_CSV_Cat_Export_Selected_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_CSV_Cat_Export_Selected.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV Export ähnelt.
        /// </summary>
        public static string UI_TxT_CSV_Cat_Export_Text {
            get {
                return ResourceManager.GetString("UI_TxT_CSV_Cat_Export.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saves this category in CSV format (Excel compatible) in a folder. ähnelt.
        /// </summary>
        public static string UI_TxT_CSV_Cat_Export_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_CSV_Cat_Export.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV Import ähnelt.
        /// </summary>
        public static string UI_TxT_CSV_Cat_Import_Text {
            get {
                return ResourceManager.GetString("UI_TxT_CSV_Cat_Import.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a CSV file whose content will be imported into this category. If the import and export categories are not identical, not all information is imported. ähnelt.
        /// </summary>
        public static string UI_TxT_CSV_Cat_Import_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_CSV_Cat_Import.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV Export ähnelt.
        /// </summary>
        public static string UI_TxT_CSV_Export_Text {
            get {
                return ResourceManager.GetString("UI_TxT_CSV_Export.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saves this character sheet in CSV format (Excel compatible) in a folder. Several files are created. ähnelt.
        /// </summary>
        public static string UI_TxT_CSV_Export_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_CSV_Export.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut ähnelt.
        /// </summary>
        public static string UI_TxT_Cut_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Cut.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string UI_TxT_Delete_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Delete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tips can be deactivated in the settings. ähnelt.
        /// </summary>
        public static string UI_Txt_DisableTips_Text {
            get {
                return ResourceManager.GetString("UI_Txt_DisableTips.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string UI_TxT_Edit_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Edit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save all in external folder ähnelt.
        /// </summary>
        public static string UI_TxT_ExportAll_Label {
            get {
                return ResourceManager.GetString("UI_TxT_ExportAll.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copies all files listed here to another folder ähnelt.
        /// </summary>
        public static string UI_TxT_ExportAll_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_ExportAll.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorize ähnelt.
        /// </summary>
        public static string UI_TxT_Fav_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Fav.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defavorize ähnelt.
        /// </summary>
        public static string UI_TxT_FavUn_Text {
            get {
                return ResourceManager.GetString("UI_TxT_FavUn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die open folder ähnelt.
        /// </summary>
        public static string UI_TxT_OpenFolder_Text {
            get {
                return ResourceManager.GetString("UI_TxT_OpenFolder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opens the folder of the current file ähnelt.
        /// </summary>
        public static string UI_TxT_OpenFolder_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_OpenFolder.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die open saveplace ähnelt.
        /// </summary>
        public static string UI_TxT_OpenFolderSTD_Label {
            get {
                return ResourceManager.GetString("UI_TxT_OpenFolderSTD.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open the folder where all your character sheets are located. ähnelt.
        /// </summary>
        public static string UI_TxT_OpenFolderSTD_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_OpenFolderSTD.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste ähnelt.
        /// </summary>
        public static string UI_TxT_Paste_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Paste.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-Fix ähnelt.
        /// </summary>
        public static string UI_TxT_Repair_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Repair.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sometimes errors occur at the link system. Then you can try this function. ähnelt.
        /// </summary>
        public static string UI_TxT_Repair_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_Repair.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string UI_TxT_Save_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Save.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saves the character sheet. ähnelt.
        /// </summary>
        public static string UI_TxT_Save_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_Save.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save at current Folder ähnelt.
        /// </summary>
        public static string UI_TxT_SaveAtCurrentPlace_Text {
            get {
                return ResourceManager.GetString("UI_TxT_SaveAtCurrentPlace.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you opened the file externally (e.g. from another program) you can save it to your normal location. ähnelt.
        /// </summary>
        public static string UI_TxT_SaveAtCurrentPlace_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_SaveAtCurrentPlace.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save at extern Folder ähnelt.
        /// </summary>
        public static string UI_TxT_SaveExtern_Text {
            get {
                return ResourceManager.GetString("UI_TxT_SaveExtern.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a new location for this file ähnelt.
        /// </summary>
        public static string UI_TxT_SaveExtern_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_SaveExtern.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Share ähnelt.
        /// </summary>
        public static string UI_TxT_Share_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Share.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subtract Lifestyle cost ähnelt.
        /// </summary>
        public static string UI_TxT_SubtractLifeStyleCost_Text {
            get {
                return ResourceManager.GetString("UI_TxT_SubtractLifeStyleCost.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tip ähnelt.
        /// </summary>
        public static string ui_txt_TipHeader_Text {
            get {
                return ResourceManager.GetString("ui_txt_TipHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unloading ähnelt.
        /// </summary>
        public static string UI_TxT_Unload_Text {
            get {
                return ResourceManager.GetString("UI_TxT_Unload.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removes only the loaded char from the app. Storage files are not affected. ähnelt.
        /// </summary>
        public static string UI_TxT_Unload_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("UI_TxT_Unload.ToolTipService.ToolTip", resourceCulture);
            }
        }
    }
}
