//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedCode.Ressourcen {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedCode.Ressourcen.ModelResources", typeof(ModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active entry: ähnelt.
        /// </summary>
        public static string _Active_Text {
            get {
                return ResourceManager.GetString("_Active.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Capacity ähnelt.
        /// </summary>
        public static string _Kapazitaet_Text {
            get {
                return ResourceManager.GetString("_Kapazitaet.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod. ähnelt.
        /// </summary>
        public static string _Mod_Text {
            get {
                return ResourceManager.GetString("_Mod.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die orig. ähnelt.
        /// </summary>
        public static string _ORG_Text {
            get {
                return ResourceManager.GetString("_ORG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pool ähnelt.
        /// </summary>
        public static string _Pool_Text {
            get {
                return ResourceManager.GetString("_Pool.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adept Power ähnelt.
        /// </summary>
        public static string Adeptenkraft__Text {
            get {
                return ResourceManager.GetString("Adeptenkraft_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string Adeptenkraft_Option_Text {
            get {
                return ResourceManager.GetString("Adeptenkraft_Option.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adept Powers ähnelt.
        /// </summary>
        public static string AdeptenkraftM__Text {
            get {
                return ResourceManager.GetString("AdeptenkraftM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attribut ähnelt.
        /// </summary>
        public static string Attribut__Text {
            get {
                return ResourceManager.GetString("Attribut_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charisma ähnelt.
        /// </summary>
        public static string Attribut_Charisma_Text {
            get {
                return ResourceManager.GetString("Attribut_Charisma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Agility ähnelt.
        /// </summary>
        public static string Attribut_Geschick_Text {
            get {
                return ResourceManager.GetString("Attribut_Geschick.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intuition ähnelt.
        /// </summary>
        public static string Attribut_Intuition_Text {
            get {
                return ResourceManager.GetString("Attribut_Intuition.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Body ähnelt.
        /// </summary>
        public static string Attribut_Konsti_Text {
            get {
                return ResourceManager.GetString("Attribut_Konsti.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logic ähnelt.
        /// </summary>
        public static string Attribut_Logik_Text {
            get {
                return ResourceManager.GetString("Attribut_Logik.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magic ähnelt.
        /// </summary>
        public static string Attribut_Magie_Text {
            get {
                return ResourceManager.GetString("Attribut_Magie.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reaction ähnelt.
        /// </summary>
        public static string Attribut_Reaktion_Text {
            get {
                return ResourceManager.GetString("Attribut_Reaktion.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resonance ähnelt.
        /// </summary>
        public static string Attribut_Resonanz_Text {
            get {
                return ResourceManager.GetString("Attribut_Resonanz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strength ähnelt.
        /// </summary>
        public static string Attribut_Staerke_Text {
            get {
                return ResourceManager.GetString("Attribut_Staerke.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willpower ähnelt.
        /// </summary>
        public static string Attribut_Willen_Text {
            get {
                return ResourceManager.GetString("Attribut_Willen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attributs ähnelt.
        /// </summary>
        public static string AttributM__Text {
            get {
                return ResourceManager.GetString("AttributM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculated value ähnelt.
        /// </summary>
        public static string Berechnet__Text {
            get {
                return ResourceManager.GetString("Berechnet_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Essence ähnelt.
        /// </summary>
        public static string Berechnet_Essenz_Text {
            get {
                return ResourceManager.GetString("Berechnet_Essenz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Walk ähnelt.
        /// </summary>
        public static string Berechnet_Laufen_Text {
            get {
                return ResourceManager.GetString("Berechnet_Laufen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mental Limit ähnelt.
        /// </summary>
        public static string Berechnet_Limit_G_Text {
            get {
                return ResourceManager.GetString("Berechnet_Limit_G.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Physical Limit ähnelt.
        /// </summary>
        public static string Berechnet_Limit_K_Text {
            get {
                return ResourceManager.GetString("Berechnet_Limit_K.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Social Limit ähnelt.
        /// </summary>
        public static string Berechnet_Limit_S_Text {
            get {
                return ResourceManager.GetString("Berechnet_Limit_S.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run ähnelt.
        /// </summary>
        public static string Berechnet_Rennen_Text {
            get {
                return ResourceManager.GetString("Berechnet_Rennen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carrie ähnelt.
        /// </summary>
        public static string Berechnet_Tragen_Text {
            get {
                return ResourceManager.GetString("Berechnet_Tragen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculated values ähnelt.
        /// </summary>
        public static string BerechnetM__Text {
            get {
                return ResourceManager.GetString("BerechnetM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact ähnelt.
        /// </summary>
        public static string Connection__Text {
            get {
                return ResourceManager.GetString("Connection_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection ähnelt.
        /// </summary>
        public static string Connection_Einfluss_Text {
            get {
                return ResourceManager.GetString("Connection_Einfluss.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loyalty ähnelt.
        /// </summary>
        public static string Connection_Loyal_Text {
            get {
                return ResourceManager.GetString("Connection_Loyal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contacts ähnelt.
        /// </summary>
        public static string ConnectionM__Text {
            get {
                return ResourceManager.GetString("ConnectionM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die memento ähnelt.
        /// </summary>
        public static string Content_Erinnerung {
            get {
                return ResourceManager.GetString("Content_Erinnerung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die knowledge of human nature ähnelt.
        /// </summary>
        public static string Content_Menschenkenntnis {
            get {
                return ResourceManager.GetString("Content_Menschenkenntnis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die damage resistance ähnelt.
        /// </summary>
        public static string Content_Schadenswiderstand {
            get {
                return ResourceManager.GetString("Content_Schadenswiderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die self-control ähnelt.
        /// </summary>
        public static string Content_Selbstbeherrschung {
            get {
                return ResourceManager.GetString("Content_Selbstbeherrschung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Deck ähnelt.
        /// </summary>
        public static string CyberDeck__Aktiv_Text {
            get {
                return ResourceManager.GetString("CyberDeck__Aktiv.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CyberDeck ähnelt.
        /// </summary>
        public static string CyberDeck__Text {
            get {
                return ResourceManager.GetString("CyberDeck_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attack Original ähnelt.
        /// </summary>
        public static string CyberDeck_Angriff_o_Text {
            get {
                return ResourceManager.GetString("CyberDeck_Angriff_o.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attack ähnelt.
        /// </summary>
        public static string CyberDeck_Angriff_Text {
            get {
                return ResourceManager.GetString("CyberDeck_Angriff.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dataprocessing original ähnelt.
        /// </summary>
        public static string CyberDeck_Datenverarbeitung_o_Text {
            get {
                return ResourceManager.GetString("CyberDeck_Datenverarbeitung_o.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firewall original ähnelt.
        /// </summary>
        public static string CyberDeck_Firewall_o_Text {
            get {
                return ResourceManager.GetString("CyberDeck_Firewall_o.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sleaze original ähnelt.
        /// </summary>
        public static string CyberDeck_Schleicher_o_Text {
            get {
                return ResourceManager.GetString("CyberDeck_Schleicher_o.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sleaze ähnelt.
        /// </summary>
        public static string CyberDeck_Schleicher_Text {
            get {
                return ResourceManager.GetString("CyberDeck_Schleicher.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CyberDecks ähnelt.
        /// </summary>
        public static string CyberDeckM__Text {
            get {
                return ResourceManager.GetString("CyberDeckM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect ähnelt.
        /// </summary>
        public static string Eigenschaft_Auswirkungen_Text {
            get {
                return ResourceManager.GetString("Eigenschaft_Auswirkungen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effects ähnelt.
        /// </summary>
        public static string Eigenschaften_Auswirkung_Text {
            get {
                return ResourceManager.GetString("Eigenschaften_Auswirkung.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Ranged Weappon ähnelt.
        /// </summary>
        public static string Fernkampfwaffe__Aktiv_Text {
            get {
                return ResourceManager.GetString("Fernkampfwaffe__Aktiv.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ranged Weapon ähnelt.
        /// </summary>
        public static string Fernkampfwaffe__Text {
            get {
                return ResourceManager.GetString("Fernkampfwaffe_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode ähnelt.
        /// </summary>
        public static string FernKampfwaffe_Modi_Text {
            get {
                return ResourceManager.GetString("FernKampfwaffe_Modi.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RC ähnelt.
        /// </summary>
        public static string Fernkampfwaffe_RK_Text {
            get {
                return ResourceManager.GetString("Fernkampfwaffe_RK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ranged Weapons ähnelt.
        /// </summary>
        public static string FernkampfwaffeM__Text {
            get {
                return ResourceManager.GetString("FernkampfwaffeM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skill ähnelt.
        /// </summary>
        public static string Fertigkeit__Text {
            get {
                return ResourceManager.GetString("Fertigkeit_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Action ähnelt.
        /// </summary>
        public static string Fertigkeit_CreateHandlung {
            get {
                return ResourceManager.GetString("Fertigkeit_CreateHandlung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skills ähnelt.
        /// </summary>
        public static string FertigkeitM__Text {
            get {
                return ResourceManager.GetString("FertigkeitM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foci ähnelt.
        /// </summary>
        public static string Foki__Text {
            get {
                return ResourceManager.GetString("Foki_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foci ähnelt.
        /// </summary>
        public static string FokiM__Text {
            get {
                return ResourceManager.GetString("FokiM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spirit ähnelt.
        /// </summary>
        public static string Geist__Text {
            get {
                return ResourceManager.GetString("Geist_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Services ähnelt.
        /// </summary>
        public static string Geist_Dienste_Text {
            get {
                return ResourceManager.GetString("Geist_Dienste.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bound ähnelt.
        /// </summary>
        public static string Geist_Geb_Reg_Text {
            get {
                return ResourceManager.GetString("Geist_Geb_Reg.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spirits ähnelt.
        /// </summary>
        public static string GeistM__Text {
            get {
                return ResourceManager.GetString("GeistM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action ähnelt.
        /// </summary>
        public static string Handlung__Text {
            get {
                return ResourceManager.GetString("Handlung_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defend dices: ähnelt.
        /// </summary>
        public static string Handlung_Gegen_Text {
            get {
                return ResourceManager.GetString("Handlung_Gegen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defense Addition ähnelt.
        /// </summary>
        public static string Handlung_GegenZusatz_Text {
            get {
                return ResourceManager.GetString("Handlung_GegenZusatz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limit: ähnelt.
        /// </summary>
        public static string Handlung_Grenze_Text {
            get {
                return ResourceManager.GetString("Handlung_Grenze.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limit Addition ähnelt.
        /// </summary>
        public static string Handlung_GrenzeZusatz_Text {
            get {
                return ResourceManager.GetString("Handlung_GrenzeZusatz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modifier ähnelt.
        /// </summary>
        public static string Handlung_Mod_Text {
            get {
                return ResourceManager.GetString("Handlung_Mod.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pool Addition ähnelt.
        /// </summary>
        public static string Handlung_WertZusatz_Text {
            get {
                return ResourceManager.GetString("Handlung_WertZusatz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dices: ähnelt.
        /// </summary>
        public static string Handlung_Zusammensetzung_Text {
            get {
                return ResourceManager.GetString("Handlung_Zusammensetzung.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string HandlungM__Text {
            get {
                return ResourceManager.GetString("HandlungM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Augmentation ähnelt.
        /// </summary>
        public static string Implantat__Text {
            get {
                return ResourceManager.GetString("Implantat_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effects ähnelt.
        /// </summary>
        public static string Implantat_Auswirkung_Text {
            get {
                return ResourceManager.GetString("Implantat_Auswirkung.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Essence ähnelt.
        /// </summary>
        public static string Implantat_Essenz_Text {
            get {
                return ResourceManager.GetString("Implantat_Essenz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Capacity ähnelt.
        /// </summary>
        public static string Implantat_Kapazitaet_Text {
            get {
                return ResourceManager.GetString("Implantat_Kapazitaet.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Augmentations ähnelt.
        /// </summary>
        public static string ImplantatM__Text {
            get {
                return ResourceManager.GetString("ImplantatM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initiation ähnelt.
        /// </summary>
        public static string Initiation__Text {
            get {
                return ResourceManager.GetString("Initiation_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Initiation_Bezeichner_Text {
            get {
                return ResourceManager.GetString("Initiation_Bezeichner.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metamagie ähnelt.
        /// </summary>
        public static string Initiation_Metamagie_Text {
            get {
                return ResourceManager.GetString("Initiation_Metamagie.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schutzpatron ähnelt.
        /// </summary>
        public static string Initiation_Schutzpatron_Text {
            get {
                return ResourceManager.GetString("Initiation_Schutzpatron.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grad ähnelt.
        /// </summary>
        public static string Initiation_Wert_Text {
            get {
                return ResourceManager.GetString("Initiation_Wert.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initiationen ähnelt.
        /// </summary>
        public static string InitiationM__Text {
            get {
                return ResourceManager.GetString("InitiationM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Item ähnelt.
        /// </summary>
        public static string Item__Text {
            get {
                return ResourceManager.GetString("Item_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active ähnelt.
        /// </summary>
        public static string Item_Aktiv_Text {
            get {
                return ResourceManager.GetString("Item_Aktiv.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantity ähnelt.
        /// </summary>
        public static string Item_Anzahl_Text {
            get {
                return ResourceManager.GetString("Item_Anzahl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Owned ähnelt.
        /// </summary>
        public static string Item_Besitz_Text {
            get {
                return ResourceManager.GetString("Item_Besitz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Items ähnelt.
        /// </summary>
        public static string ItemM__Text {
            get {
                return ResourceManager.GetString("ItemM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Commlink ähnelt.
        /// </summary>
        public static string Kommlink__Aktiv_Text {
            get {
                return ResourceManager.GetString("Kommlink__Aktiv.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commlink ähnelt.
        /// </summary>
        public static string Kommlink__Text {
            get {
                return ResourceManager.GetString("Kommlink_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attributes ähnelt.
        /// </summary>
        public static string Kommlink_Attribute_o_Text {
            get {
                return ResourceManager.GetString("Kommlink_Attribute_o.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attributes ähnelt.
        /// </summary>
        public static string Kommlink_Attribute_Text {
            get {
                return ResourceManager.GetString("Kommlink_Attribute.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Processing ähnelt.
        /// </summary>
        public static string Kommlink_Datenverarbeitung_Text {
            get {
                return ResourceManager.GetString("Kommlink_Datenverarbeitung.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firewall ähnelt.
        /// </summary>
        public static string Kommlink_Firewall_Text {
            get {
                return ResourceManager.GetString("Kommlink_Firewall.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programms ähnelt.
        /// </summary>
        public static string Kommlink_Programmanzahl_Text {
            get {
                return ResourceManager.GetString("Kommlink_Programmanzahl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Condition ähnelt.
        /// </summary>
        public static string Kommlink_Schaden_Text {
            get {
                return ResourceManager.GetString("Kommlink_Schaden.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Condition Limit ähnelt.
        /// </summary>
        public static string Kommlink_SchadenMax_Text {
            get {
                return ResourceManager.GetString("Kommlink_SchadenMax.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commlinks ähnelt.
        /// </summary>
        public static string KommlinkM__Text {
            get {
                return ResourceManager.GetString("KommlinkM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complex Form ähnelt.
        /// </summary>
        public static string KomplexeForm__Text {
            get {
                return ResourceManager.GetString("KomplexeForm_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Option ähnelt.
        /// </summary>
        public static string KomplexeForm_Option_Text {
            get {
                return ResourceManager.GetString("KomplexeForm_Option.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complex Forms ähnelt.
        /// </summary>
        public static string KomplexeFormM__Text {
            get {
                return ResourceManager.GetString("KomplexeFormM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration ähnelt.
        /// </summary>
        public static string KomplexForm_Duration_Text {
            get {
                return ResourceManager.GetString("KomplexForm_Duration.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fading ähnelt.
        /// </summary>
        public static string KomplexForm_Fading_Text {
            get {
                return ResourceManager.GetString("KomplexForm_Fading.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target ähnelt.
        /// </summary>
        public static string KomplexForm_Target_Text {
            get {
                return ResourceManager.GetString("KomplexForm_Target.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Munition ähnelt.
        /// </summary>
        public static string Munition__Text {
            get {
                return ResourceManager.GetString("Munition_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Munitions ähnelt.
        /// </summary>
        public static string MunitionM__Text {
            get {
                return ResourceManager.GetString("MunitionM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disadvantage ähnelt.
        /// </summary>
        public static string Nachteil__Text {
            get {
                return ResourceManager.GetString("Nachteil_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disadvantages ähnelt.
        /// </summary>
        public static string NachteilM__Text {
            get {
                return ResourceManager.GetString("NachteilM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Melee Weapon ähnelt.
        /// </summary>
        public static string Nahkampfwaffe__Aktiv_Text {
            get {
                return ResourceManager.GetString("Nahkampfwaffe__Aktiv.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Melee Weapon ähnelt.
        /// </summary>
        public static string Nahkampfwaffe__Text {
            get {
                return ResourceManager.GetString("Nahkampfwaffe_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reach ähnelt.
        /// </summary>
        public static string Nahkampfwaffe_Reichweite_Text {
            get {
                return ResourceManager.GetString("Nahkampfwaffe_Reichweite.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Melee Weapons ähnelt.
        /// </summary>
        public static string NahkampfwaffeM__Text {
            get {
                return ResourceManager.GetString("NahkampfwaffeM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Armor ähnelt.
        /// </summary>
        public static string Panzerung__Aktiv_Text {
            get {
                return ResourceManager.GetString("Panzerung__Aktiv.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Armor ähnelt.
        /// </summary>
        public static string Panzerung__Text {
            get {
                return ResourceManager.GetString("Panzerung_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Capacity ähnelt.
        /// </summary>
        public static string Panzerung_Kapazitaet_Text {
            get {
                return ResourceManager.GetString("Panzerung_Kapazitaet.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Armors ähnelt.
        /// </summary>
        public static string PanzerungM__Text {
            get {
                return ResourceManager.GetString("PanzerungM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personal data ähnelt.
        /// </summary>
        public static string Person__Text {
            get {
                return ResourceManager.GetString("Person_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Person_Alias_STD_Text {
            get {
                return ResourceManager.GetString("Person_Alias_STD.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alias ähnelt.
        /// </summary>
        public static string Person_Alias_Text {
            get {
                return ResourceManager.GetString("Person_Alias.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eyecolour ähnelt.
        /// </summary>
        public static string Person_Augenfarbe_Text {
            get {
                return ResourceManager.GetString("Person_Augenfarbe.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personal description ähnelt.
        /// </summary>
        public static string Person_Beschreibung__Text {
            get {
                return ResourceManager.GetString("Person_Beschreibung_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Char Type ähnelt.
        /// </summary>
        public static string Person_Char_Typ_Text {
            get {
                return ResourceManager.GetString("Person_Char_Typ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edge current ähnelt.
        /// </summary>
        public static string Person_Edge_Aktuell_Text {
            get {
                return ResourceManager.GetString("Person_Edge_Aktuell.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edge everall ähnelt.
        /// </summary>
        public static string Person_Edge_Gesamt_Text {
            get {
                return ResourceManager.GetString("Person_Edge_Gesamt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edge ähnelt.
        /// </summary>
        public static string Person_Edge_Text {
            get {
                return ResourceManager.GetString("Person_Edge.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Essence mod ähnelt.
        /// </summary>
        public static string Person_Essenz_Text {
            get {
                return ResourceManager.GetString("Person_Essenz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date of Birth ähnelt.
        /// </summary>
        public static string Person_Geburtsdatum_Text {
            get {
                return ResourceManager.GetString("Person_Geburtsdatum.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birthday ähnelt.
        /// </summary>
        public static string Person_Geburtstag_Text {
            get {
                return ResourceManager.GetString("Person_Geburtstag.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sex ähnelt.
        /// </summary>
        public static string Person_Geschlecht_Text {
            get {
                return ResourceManager.GetString("Person_Geschlecht.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weight ähnelt.
        /// </summary>
        public static string Person_Gewicht_Text {
            get {
                return ResourceManager.GetString("Person_Gewicht.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height ähnelt.
        /// </summary>
        public static string Person_Groesse_Text {
            get {
                return ResourceManager.GetString("Person_Groesse.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Haircolor ähnelt.
        /// </summary>
        public static string Person_Haarfarbe_Text {
            get {
                return ResourceManager.GetString("Person_Haarfarbe.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skincolor ähnelt.
        /// </summary>
        public static string Person_Hautfarbe_Text {
            get {
                return ResourceManager.GetString("Person_Hautfarbe.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ini ähnelt.
        /// </summary>
        public static string Person_Initiative_Kurz_Text {
            get {
                return ResourceManager.GetString("Person_Initiative_Kurz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initiative  ähnelt.
        /// </summary>
        public static string Person_Initiative_Text {
            get {
                return ResourceManager.GetString("Person_Initiative.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current initiative ähnelt.
        /// </summary>
        public static string Person_InitiativeAktuell_Text {
            get {
                return ResourceManager.GetString("Person_InitiativeAktuell.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Karma Current ähnelt.
        /// </summary>
        public static string Person_Karma_Aktuell_Text {
            get {
                return ResourceManager.GetString("Person_Karma_Aktuell.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Karma total ähnelt.
        /// </summary>
        public static string Person_Karma_Gesamt_Text {
            get {
                return ResourceManager.GetString("Person_Karma_Gesamt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Karma ähnelt.
        /// </summary>
        public static string Person_Karma_Text {
            get {
                return ResourceManager.GetString("Person_Karma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank balance ähnelt.
        /// </summary>
        public static string Person_Kontostand_Text {
            get {
                return ResourceManager.GetString("Person_Kontostand.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lifestyle ähnelt.
        /// </summary>
        public static string Person_Lebensstil_Text {
            get {
                return ResourceManager.GetString("Person_Lebensstil.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lifestyle cost ähnelt.
        /// </summary>
        public static string Person_LifestyleCost_Text {
            get {
                return ResourceManager.GetString("Person_LifestyleCost.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metasubtype ähnelt.
        /// </summary>
        public static string Person_MetaTyp_sub_Text {
            get {
                return ResourceManager.GetString("Person_MetaTyp_sub.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metatype ähnelt.
        /// </summary>
        public static string Person_MetaTyp_Text {
            get {
                return ResourceManager.GetString("Person_MetaTyp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        public static string Person_Notizen_Text {
            get {
                return ResourceManager.GetString("Person_Notizen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Public Awareness ähnelt.
        /// </summary>
        public static string Person_Prominenz_Text {
            get {
                return ResourceManager.GetString("Person_Prominenz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runs ähnelt.
        /// </summary>
        public static string Person_Runs_Text {
            get {
                return ResourceManager.GetString("Person_Runs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max. Physical-Damage modifier ähnelt.
        /// </summary>
        public static string Person_Schaden_G_max_mod_Text {
            get {
                return ResourceManager.GetString("Person_Schaden_G_max_mod.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mental Damage Maximum ähnelt.
        /// </summary>
        public static string Person_Schaden_G_max_Text {
            get {
                return ResourceManager.GetString("Person_Schaden_G_max.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mental Damage ähnelt.
        /// </summary>
        public static string Person_Schaden_G_Text {
            get {
                return ResourceManager.GetString("Person_Schaden_G.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max. Mental-Damage modifier ähnelt.
        /// </summary>
        public static string Person_Schaden_K_max_mod_Text {
            get {
                return ResourceManager.GetString("Person_Schaden_K_max_mod.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Physical Damage Maximum ähnelt.
        /// </summary>
        public static string Person_Schaden_K_max_Text {
            get {
                return ResourceManager.GetString("Person_Schaden_K_max.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Physical Damage  ähnelt.
        /// </summary>
        public static string Person_Schaden_K_Text {
            get {
                return ResourceManager.GetString("Person_Schaden_K.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bad reputation ähnelt.
        /// </summary>
        public static string Person_SchlechterRuf_Text {
            get {
                return ResourceManager.GetString("Person_SchlechterRuf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Street Cred ähnelt.
        /// </summary>
        public static string Person_Strassenruf_Text {
            get {
                return ResourceManager.GetString("Person_Strassenruf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Street Cred mod ähnelt.
        /// </summary>
        public static string Person_StrassenrufMod_Text {
            get {
                return ResourceManager.GetString("Person_StrassenrufMod.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summary ähnelt.
        /// </summary>
        public static string Person_Zusammenfassung_Text {
            get {
                return ResourceManager.GetString("Person_Zusammenfassung.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program ähnelt.
        /// </summary>
        public static string Programm__Text {
            get {
                return ResourceManager.GetString("Programm_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effects ähnelt.
        /// </summary>
        public static string Programm_Optionen_Text {
            get {
                return ResourceManager.GetString("Programm_Optionen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programs ähnelt.
        /// </summary>
        public static string ProgrammM__Text {
            get {
                return ResourceManager.GetString("ProgrammM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SIN ähnelt.
        /// </summary>
        public static string SIN__Text {
            get {
                return ResourceManager.GetString("SIN_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SINs ähnelt.
        /// </summary>
        public static string SINM__Text {
            get {
                return ResourceManager.GetString("SINM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprite ähnelt.
        /// </summary>
        public static string Sprite__Text {
            get {
                return ResourceManager.GetString("Sprite_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Services ähnelt.
        /// </summary>
        public static string Sprite_Dienste_Text {
            get {
                return ResourceManager.GetString("Sprite_Dienste.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registered ähnelt.
        /// </summary>
        public static string Sprite_Geb_Reg_Text {
            get {
                return ResourceManager.GetString("Sprite_Geb_Reg.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprites ähnelt.
        /// </summary>
        public static string SpriteM__Text {
            get {
                return ResourceManager.GetString("SpriteM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submersion ähnelt.
        /// </summary>
        public static string Stroemung__Text {
            get {
                return ResourceManager.GetString("Stroemung_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Stroemung_Bezeichner_Text {
            get {
                return ResourceManager.GetString("Stroemung_Bezeichner.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Echoes ähnelt.
        /// </summary>
        public static string Stroemung_Echos_Text {
            get {
                return ResourceManager.GetString("Stroemung_Echos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paragon ähnelt.
        /// </summary>
        public static string Stroemung_Paragon_Text {
            get {
                return ResourceManager.GetString("Stroemung_Paragon.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grade ähnelt.
        /// </summary>
        public static string Stroemung_Wert_Text {
            get {
                return ResourceManager.GetString("Stroemung_Wert.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submersions ähnelt.
        /// </summary>
        public static string StroemungM__Text {
            get {
                return ResourceManager.GetString("StroemungM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Thing_Bezeichner_Text {
            get {
                return ResourceManager.GetString("Thing_Bezeichner.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorit ähnelt.
        /// </summary>
        public static string Thing_IsFavorite_Text {
            get {
                return ResourceManager.GetString("Thing_IsFavorite.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Note ähnelt.
        /// </summary>
        public static string Thing_Notiz_Text {
            get {
                return ResourceManager.GetString("Thing_Notiz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ThingType ähnelt.
        /// </summary>
        public static string Thing_ThingTyp_Text {
            get {
                return ResourceManager.GetString("Thing_ThingTyp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string Thing_Typ_Text {
            get {
                return ResourceManager.GetString("Thing_Typ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rating ähnelt.
        /// </summary>
        public static string Thing_Wert_Text {
            get {
                return ResourceManager.GetString("Thing_Wert.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string Thing_Wert_W_Text {
            get {
                return ResourceManager.GetString("Thing_Wert_W.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Addition ähnelt.
        /// </summary>
        public static string Thing_Zusatz_Text {
            get {
                return ResourceManager.GetString("Thing_Zusatz.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tradition ähnelt.
        /// </summary>
        public static string Tradition__Text {
            get {
                return ResourceManager.GetString("Tradition_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NameEN ähnelt.
        /// </summary>
        public static string Tradition_Bezeichner_Text {
            get {
                return ResourceManager.GetString("Tradition_Bezeichner.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metamagic ähnelt.
        /// </summary>
        public static string Tradition_Metamagie_Text {
            get {
                return ResourceManager.GetString("Tradition_Metamagie.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Totem ähnelt.
        /// </summary>
        public static string Tradition_Schutzpatron_Text {
            get {
                return ResourceManager.GetString("Tradition_Schutzpatron.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grade ähnelt.
        /// </summary>
        public static string Tradition_Wert_Text {
            get {
                return ResourceManager.GetString("Tradition_Wert.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Traditions ähnelt.
        /// </summary>
        public static string TraditionM__Text {
            get {
                return ResourceManager.GetString("TraditionM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active vehicle ähnelt.
        /// </summary>
        public static string Vehikel__Aktiv_Text {
            get {
                return ResourceManager.GetString("Vehikel__Aktiv.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle ähnelt.
        /// </summary>
        public static string Vehikel__Text {
            get {
                return ResourceManager.GetString("Vehikel_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acceleration ähnelt.
        /// </summary>
        public static string Vehikel_Beschleunigung_Text {
            get {
                return ResourceManager.GetString("Vehikel_Beschleunigung.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ähnelt.
        /// </summary>
        public static string Vehikel_Geschwindigkeit_Text {
            get {
                return ResourceManager.GetString("Vehikel_Geschwindigkeit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weight ähnelt.
        /// </summary>
        public static string Vehikel_Gewicht_Text {
            get {
                return ResourceManager.GetString("Vehikel_Gewicht.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Handling ähnelt.
        /// </summary>
        public static string Vehikel_Handling_Text {
            get {
                return ResourceManager.GetString("Vehikel_Handling.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Armor ähnelt.
        /// </summary>
        public static string Vehikel_Panzerung_Text {
            get {
                return ResourceManager.GetString("Vehikel_Panzerung.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pilot ähnelt.
        /// </summary>
        public static string Vehikel_Pilot_Text {
            get {
                return ResourceManager.GetString("Vehikel_Pilot.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Body ähnelt.
        /// </summary>
        public static string Vehikel_Rumpf_Text {
            get {
                return ResourceManager.GetString("Vehikel_Rumpf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor ähnelt.
        /// </summary>
        public static string Vehikel_Sensor_Text {
            get {
                return ResourceManager.GetString("Vehikel_Sensor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seats ähnelt.
        /// </summary>
        public static string Vehikel_Sitze_Text {
            get {
                return ResourceManager.GetString("Vehikel_Sitze.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Damage ähnelt.
        /// </summary>
        public static string Vehikel_Wert_Text {
            get {
                return ResourceManager.GetString("Vehikel_Wert.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicles ähnelt.
        /// </summary>
        public static string VehikelM__Text {
            get {
                return ResourceManager.GetString("VehikelM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advantage ähnelt.
        /// </summary>
        public static string Vorteil__Text {
            get {
                return ResourceManager.GetString("Vorteil_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advantages ähnelt.
        /// </summary>
        public static string VorteilM__Text {
            get {
                return ResourceManager.GetString("VorteilM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AP ähnelt.
        /// </summary>
        public static string Waffe_DK_Text {
            get {
                return ResourceManager.GetString("Waffe_DK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Precision ähnelt.
        /// </summary>
        public static string Waffe_Praezision_Text {
            get {
                return ResourceManager.GetString("Waffe_Praezision.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Damage type (M/P) ähnelt.
        /// </summary>
        public static string Waffe_SchadenTyp_Text {
            get {
                return ResourceManager.GetString("Waffe_SchadenTyp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Damage ähnelt.
        /// </summary>
        public static string Waffe_Wert_Text {
            get {
                return ResourceManager.GetString("Waffe_Wert.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submersion ähnelt.
        /// </summary>
        public static string Wandlung__Text {
            get {
                return ResourceManager.GetString("Wandlung_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Wandlung_Bezeichner_Text {
            get {
                return ResourceManager.GetString("Wandlung_Bezeichner.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Echos ähnelt.
        /// </summary>
        public static string Wandlung_Echos_Text {
            get {
                return ResourceManager.GetString("Wandlung_Echos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paragon ähnelt.
        /// </summary>
        public static string Wandlung_Paragon_Text {
            get {
                return ResourceManager.GetString("Wandlung_Paragon.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grad ähnelt.
        /// </summary>
        public static string Wandlung_Wert_Text {
            get {
                return ResourceManager.GetString("Wandlung_Wert.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submersions ähnelt.
        /// </summary>
        public static string WandlungM__Text {
            get {
                return ResourceManager.GetString("WandlungM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Widget ähnelt.
        /// </summary>
        public static string Widgets__Text {
            get {
                return ResourceManager.GetString("Widgets_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Widgets ähnelt.
        /// </summary>
        public static string WidgetsM__Text {
            get {
                return ResourceManager.GetString("WidgetsM_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spell ähnelt.
        /// </summary>
        public static string Zaubersprueche__Text {
            get {
                return ResourceManager.GetString("Zaubersprueche_.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration ähnelt.
        /// </summary>
        public static string Zaubersprueche_Dauer_Text {
            get {
                return ResourceManager.GetString("Zaubersprueche_Dauer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drain ähnelt.
        /// </summary>
        public static string Zaubersprueche_Entzug_Text {
            get {
                return ResourceManager.GetString("Zaubersprueche_Entzug.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Range ähnelt.
        /// </summary>
        public static string Zaubersprueche_Reichweite_Text {
            get {
                return ResourceManager.GetString("Zaubersprueche_Reichweite.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spells ähnelt.
        /// </summary>
        public static string ZauberspruecheM__Text {
            get {
                return ResourceManager.GetString("ZauberspruecheM_.Text", resourceCulture);
            }
        }
    }
}
