//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedCode.Ressourcen {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedCode.Ressourcen.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administration ähnelt.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Seperator ähnelt.
        /// </summary>
        public static string Cat_AddSep {
            get {
                return ResourceManager.GetString("Cat_AddSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort alphabeticly ähnelt.
        /// </summary>
        public static string Cat_Order_ABC {
            get {
                return ResourceManager.GetString("Cat_Order_ABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load saved order ähnelt.
        /// </summary>
        public static string Cat_Order_Orig {
            get {
                return ResourceManager.GetString("Cat_Order_Orig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loads the previously saved sequence of the entry of this category. ähnelt.
        /// </summary>
        public static string Cat_Order_OrigX {
            get {
                return ResourceManager.GetString("Cat_Order_OrigX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save current order ähnelt.
        /// </summary>
        public static string Cat_Order_Save {
            get {
                return ResourceManager.GetString("Cat_Order_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saves the current sequence of the entry of this category. ähnelt.
        /// </summary>
        public static string Cat_Order_SaveX {
            get {
                return ResourceManager.GetString("Cat_Order_SaveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort after &quot;type&quot; ähnelt.
        /// </summary>
        public static string Cat_Order_Type {
            get {
                return ResourceManager.GetString("Cat_Order_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string Category_Aktion {
            get {
                return ResourceManager.GetString("Category_Aktion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Items ähnelt.
        /// </summary>
        public static string Category_Item {
            get {
                return ResourceManager.GetString("Category_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battle ähnelt.
        /// </summary>
        public static string Category_Kampf {
            get {
                return ResourceManager.GetString("Category_Kampf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        public static string Category_Notizen {
            get {
                return ResourceManager.GetString("Category_Notizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Person ähnelt.
        /// </summary>
        public static string Category_Person {
            get {
                return ResourceManager.GetString("Category_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Category_Settings {
            get {
                return ResourceManager.GetString("Category_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mental ähnelt.
        /// </summary>
        public static string Char_Schaden_Geist {
            get {
                return ResourceManager.GetString("Char_Schaden_Geist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Physical ähnelt.
        /// </summary>
        public static string Char_Schaden_Koerper {
            get {
                return ResourceManager.GetString("Char_Schaden_Koerper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Matrix ähnelt.
        /// </summary>
        public static string Char_Schaden_Matrix {
            get {
                return ResourceManager.GetString("Char_Schaden_Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character Sheet ähnelt.
        /// </summary>
        public static string CharacterSheet {
            get {
                return ResourceManager.GetString("CharacterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character sheet settings ähnelt.
        /// </summary>
        public static string CharSettings {
            get {
                return ResourceManager.GetString("CharSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Example Char ähnelt.
        /// </summary>
        public static string CreateExampleChar {
            get {
                return ResourceManager.GetString("CreateExampleChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new char ähnelt.
        /// </summary>
        public static string CreateNewChar {
            get {
                return ResourceManager.GetString("CreateNewChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create something new! ähnelt.
        /// </summary>
        public static string CreateSomethingNew {
            get {
                return ResourceManager.GetString("CreateSomethingNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut ähnelt.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Damage ähnelt.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tips can be deactivated in the settings. ähnelt.
        /// </summary>
        public static string DisableTips {
            get {
                return ResourceManager.GetString("DisableTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current savefiles: ähnelt.
        /// </summary>
        public static string Einleitung1 {
            get {
                return ResourceManager.GetString("Einleitung1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available savefiles: ähnelt.
        /// </summary>
        public static string Einleitung2 {
            get {
                return ResourceManager.GetString("Einleitung2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Its empty here ... ähnelt.
        /// </summary>
        public static string EmptyHere {
            get {
                return ResourceManager.GetString("EmptyHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save all in external folder ähnelt.
        /// </summary>
        public static string ExportAll {
            get {
                return ResourceManager.GetString("ExportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy this file to another location. ähnelt.
        /// </summary>
        public static string ExportTip {
            get {
                return ResourceManager.GetString("ExportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorize ähnelt.
        /// </summary>
        public static string Fav {
            get {
                return ResourceManager.GetString("Fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defavorize ähnelt.
        /// </summary>
        public static string FavUn {
            get {
                return ResourceManager.GetString("FavUn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die modification date ähnelt.
        /// </summary>
        public static string FileDate {
            get {
                return ResourceManager.GetString("FileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletes this file permanently ähnelt.
        /// </summary>
        public static string FileDeleteTip {
            get {
                return ResourceManager.GetString("FileDeleteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Char Export ähnelt.
        /// </summary>
        public static string FileExport {
            get {
                return ResourceManager.GetString("FileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename ähnelt.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        public static string FileRename {
            get {
                return ResourceManager.GetString("FileRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filesize ähnelt.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Input ähnelt.
        /// </summary>
        public static string GeneralInput {
            get {
                return ResourceManager.GetString("GeneralInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Char ähnelt.
        /// </summary>
        public static string ImportChar {
            get {
                return ResourceManager.GetString("ImportChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a Entry from the list below to load a charactersheet or create a new one. ähnelt.
        /// </summary>
        public static string IntroAdministration {
            get {
                return ResourceManager.GetString("IntroAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More ähnelt.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new char ähnelt.
        /// </summary>
        public static string NewChar {
            get {
                return ResourceManager.GetString("NewChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        public static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On ähnelt.
        /// </summary>
        public static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die open folder ähnelt.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open notifications ähnelt.
        /// </summary>
        public static string OpenNotifications {
            get {
                return ResourceManager.GetString("OpenNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App ähnelt.
        /// </summary>
        public static string Options_App {
            get {
                return ResourceManager.GetString("Options_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Storeentry for this App ähnelt.
        /// </summary>
        public static string Options_AppLinkBtn {
            get {
                return ResourceManager.GetString("Options_AppLinkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automated saves for chars ähnelt.
        /// </summary>
        public static string Options_AutoSave {
            get {
                return ResourceManager.GetString("Options_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Watingtime for changes in seconds ähnelt.
        /// </summary>
        public static string Options_AutoSaveInterval {
            get {
                return ResourceManager.GetString("Options_AutoSaveInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After a change, the specified time is waited until your char is saved. If you change many things quickly, then a larger value is better. A value between 2 and 10 seconds is okay. ähnelt.
        /// </summary>
        public static string Options_AutoSaveTip {
            get {
                return ResourceManager.GetString("Options_AutoSaveTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BackUp versioning ähnelt.
        /// </summary>
        public static string Options_BACKUP_VERSIONING {
            get {
                return ResourceManager.GetString("Options_BACKUP_VERSIONING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activate Beta-Features ähnelt.
        /// </summary>
        public static string Options_Beta_Features {
            get {
                return ResourceManager.GetString("Options_Beta_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rate this App at the Store ähnelt.
        /// </summary>
        public static string Options_Bewerten {
            get {
                return ResourceManager.GetString("Options_Bewerten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This app does not collect any personal information and therefore does not disclose it.
        ///This app can be used to open files and folders on the file system. The app stores those folders and files only for later use. All files remain on the file system or Microsoft account. ähnelt.
        /// </summary>
        public static string Options_Datenschutz {
            get {
                return ResourceManager.GetString("Options_Datenschutz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prevent ScreenLock ähnelt.
        /// </summary>
        public static string Options_DisplayRequest {
            get {
                return ResourceManager.GetString("Options_DisplayRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prevent the Screen from locking, if have an open char. ähnelt.
        /// </summary>
        public static string Options_DisplayRequestTip {
            get {
                return ResourceManager.GetString("Options_DisplayRequestTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit after add ähnelt.
        /// </summary>
        public static string Options_EditAfterAdd {
            get {
                return ResourceManager.GetString("Options_EditAfterAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After you have created an object, the edit dialog is called immediately. ähnelt.
        /// </summary>
        public static string Options_EditAfterAddTip {
            get {
                return ResourceManager.GetString("Options_EditAfterAddTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Char ähnelt.
        /// </summary>
        public static string Options_Group_Char {
            get {
                return ResourceManager.GetString("Options_Group_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filemanagement ähnelt.
        /// </summary>
        public static string Options_Group_File {
            get {
                return ResourceManager.GetString("Options_Group_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving and loading ähnelt.
        /// </summary>
        public static string Options_Group_IO {
            get {
                return ResourceManager.GetString("Options_Group_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App owener ähnelt.
        /// </summary>
        public static string Options_Inhaber {
            get {
                return ResourceManager.GetString("Options_Inhaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die email ähnelt.
        /// </summary>
        public static string Options_Kontakt_Mail {
            get {
                return ResourceManager.GetString("Options_Kontakt_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ShadowRun is a registered trademark of Pegasus Games.
        ///Icons made by Freepik https://www.flaticon.com are licensed by Creative Commons BY 3.0. ähnelt.
        /// </summary>
        public static string Options_Legal {
            get {
                return ResourceManager.GetString("Options_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load last char at startup ähnelt.
        /// </summary>
        public static string Options_LoadOnStart {
            get {
                return ResourceManager.GetString("Options_LoadOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The char that was active when the app was closed is loaded at startup. Attention, this increases the app loading time. ähnelt.
        /// </summary>
        public static string Options_LoadOnStartTip {
            get {
                return ResourceManager.GetString("Options_LoadOnStartTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die more of my apps ähnelt.
        /// </summary>
        public static string Options_MoreAppsBtn {
            get {
                return ResourceManager.GetString("Options_MoreAppsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a Exernen storage folder. ähnelt.
        /// </summary>
        public static string Options_Ordnermode {
            get {
                return ResourceManager.GetString("Options_Ordnermode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path ähnelt.
        /// </summary>
        public static string Options_Ordnermode_Pfad {
            get {
                return ResourceManager.GetString("Options_Ordnermode_Pfad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rate this App ähnelt.
        /// </summary>
        public static string Options_RateBtn {
            get {
                return ResourceManager.GetString("Options_RateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original Exception ähnelt.
        /// </summary>
        public static string Options_ThrownException {
            get {
                return ResourceManager.GetString("Options_ThrownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read &quot;Char Administration&quot; Guide ähnelt.
        /// </summary>
        public static string Options_TutorialMainShown {
            get {
                return ResourceManager.GetString("Options_TutorialMainShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy ähnelt.
        /// </summary>
        public static string Options_U_Buy {
            get {
                return ResourceManager.GetString("Options_U_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you have the possibility to make purchases. You can turn off advertising with the first two options. The third option supports the developer and adds an exclusive Badge to your app. ähnelt.
        /// </summary>
        public static string Options_U_Buying_Header {
            get {
                return ResourceManager.GetString("Options_U_Buying_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Note: Having apps in the store costs 18€ per year. It would be cool if the app would at least cover the costs. ähnelt.
        /// </summary>
        public static string Options_U_Buying_Note {
            get {
                return ResourceManager.GetString("Options_U_Buying_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose categories ähnelt.
        /// </summary>
        public static string Options_U_CharPageConfig {
            get {
                return ResourceManager.GetString("Options_U_CharPageConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy Policy ähnelt.
        /// </summary>
        public static string Options_U_Datenschutz {
            get {
                return ResourceManager.GetString("Options_U_Datenschutz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string Options_U_Hilfe {
            get {
                return ResourceManager.GetString("Options_U_Hilfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string Options_U_Infos {
            get {
                return ResourceManager.GetString("Options_U_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact ähnelt.
        /// </summary>
        public static string Options_U_Kontakt {
            get {
                return ResourceManager.GetString("Options_U_Kontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications ähnelt.
        /// </summary>
        public static string Options_U_Notifications {
            get {
                return ResourceManager.GetString("Options_U_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legal ähnelt.
        /// </summary>
        public static string Options_U_Rechtliches {
            get {
                return ResourceManager.GetString("Options_U_Rechtliches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics ähnelt.
        /// </summary>
        public static string Options_U_Statistics {
            get {
                return ResourceManager.GetString("Options_U_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string Options_Version {
            get {
                return ResourceManager.GetString("Options_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste ähnelt.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-Fix ähnelt.
        /// </summary>
        public static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sometimes errors occur at the link system. Then you can try this function. ähnelt.
        /// </summary>
        public static string RepairTip {
            get {
                return ResourceManager.GetString("RepairTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save at current Folder ähnelt.
        /// </summary>
        public static string SaveAtCurrentPlace {
            get {
                return ResourceManager.GetString("SaveAtCurrentPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you opened the file externally (e.g. from another program) you can save it to your normal location. ähnelt.
        /// </summary>
        public static string SaveAtCurrentPlaceTip {
            get {
                return ResourceManager.GetString("SaveAtCurrentPlaceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save at extern Folder ähnelt.
        /// </summary>
        public static string SaveExtern {
            get {
                return ResourceManager.GetString("SaveExtern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a new location for this file ähnelt.
        /// </summary>
        public static string SaveExternTip {
            get {
                return ResourceManager.GetString("SaveExternTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saves the character sheet. ähnelt.
        /// </summary>
        public static string SaveTip {
            get {
                return ResourceManager.GetString("SaveTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search for entries ... ähnelt.
        /// </summary>
        public static string SearchForEntries {
            get {
                return ResourceManager.GetString("SearchForEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hold the mouse or finger on a ? to get more information. ähnelt.
        /// </summary>
        public static string Settings_Tip {
            get {
                return ResourceManager.GetString("Settings_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Share ähnelt.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of appstarts ähnelt.
        /// </summary>
        public static string Statistics_AppStart {
            get {
                return ResourceManager.GetString("Statistics_AppStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of new chars ähnelt.
        /// </summary>
        public static string Statistics_Creations {
            get {
                return ResourceManager.GetString("Statistics_Creations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of deleted chars ähnelt.
        /// </summary>
        public static string Statistics_Deletions {
            get {
                return ResourceManager.GetString("Statistics_Deletions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of loaded chars ähnelt.
        /// </summary>
        public static string Statistics_Loadings {
            get {
                return ResourceManager.GetString("Statistics_Loadings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of saved chars ähnelt.
        /// </summary>
        public static string Statistics_Savings {
            get {
                return ResourceManager.GetString("Statistics_Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subtract Lifestyle cost ähnelt.
        /// </summary>
        public static string SubtractLifeStyleCost {
            get {
                return ResourceManager.GetString("SubtractLifeStyleCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tap again to exit ähnelt.
        /// </summary>
        public static string TapAgainToExit {
            get {
                return ResourceManager.GetString("TapAgainToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change UPPER CASE to Normal case in name and note ähnelt.
        /// </summary>
        public static string TextRefactoring_Case {
            get {
                return ResourceManager.GetString("TextRefactoring_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove LineBreaks in Notes ähnelt.
        /// </summary>
        public static string TextRefactoring_NewLine {
            get {
                return ResourceManager.GetString("TextRefactoring_NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tip ähnelt.
        /// </summary>
        public static string TipHeader {
            get {
                return ResourceManager.GetString("TipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info and Settings ähnelt.
        /// </summary>
        public static string TitleMiscPage {
            get {
                return ResourceManager.GetString("TitleMiscPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info and Settings ähnelt.
        /// </summary>
        public static string TitleOtherPage {
            get {
                return ResourceManager.GetString("TitleOtherPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Unload {
            get {
                return ResourceManager.GetString("Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removes only the loaded char from the app. Storage files are not affected. ähnelt.
        /// </summary>
        public static string UnloadX {
            get {
                return ResourceManager.GetString("UnloadX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning, you are saving your chars locally at the moment. It is strongly recommendet to use an synchronized folder like OneDrive or DropBox or an SD Card. Tap on this message to do so. ähnelt.
        /// </summary>
        public static string WarningLocalSaveplace {
            get {
                return ResourceManager.GetString("WarningLocalSaveplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to ShadowRunHelper ähnelt.
        /// </summary>
        public static string WelcomeGreetings {
            get {
                return ResourceManager.GetString("WelcomeGreetings", resourceCulture);
            }
        }
    }
}
